name=ACANFD_SAME
version=1.0.0
author=Pierre Molinaro, Terry Gould
sentence=CAN FD library for SAME5x MCUs derived from ACANFD_FeatherM4CAN by Pierre Molinaro
paragraph=Based on ACANFD_FeatherM4CAN with added BSP-driven pin detection, multi-board support and portability improvements. Compatible with ACAN2515, ACAN2517, ACAN2517FD libraries. Default configuration sends and receives any frame – no default filter to provide. Standard reception filters (up to 128) and extended reception filters (up to 128) can be easily defined.
category=Communication
architectures=*